ALTER TYPE "RoomStatus" ADD VALUE 'LADY_INSPECTION';
ALTER TABLE "Room" ADD COLUMN "ladyHolderId" TEXT,
ADD COLUMN "ladyPreviousHolders" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "ladyRecords" JSONB NOT NULL DEFAULT '[]';
